# Generated by Django 2.2 on 2019-06-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20190614_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ans_count',
            field=models.IntegerField(default=0, verbose_name='Количество ответов'),
        ),
    ]
