# Generated by Django 2.2 on 2019-06-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_ans_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/img/Arcadia64', upload_to='static/img/'),
        ),
    ]
