# Generated by Django 2.2 on 2019-06-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20190614_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/img/Arcadia64.jpg', upload_to='static/img/'),
        ),
    ]
