# Generated by Django 2.2 on 2019-06-16 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20190614_2221'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'answer'), ('user', 'question')},
        ),
    ]
