# Generated by Django 2.2 on 2019-06-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20190618_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='type',
            field=models.CharField(choices=[('Like', '+'), ('Dislike', '-')], default='Like', max_length=2),
        ),
    ]
